name: Ping Website

on:
  schedule:
    - cron: '*/14 * * * *'  # Every 14 minutes UTC
  workflow_dispatch:        # Allows manual runs from GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl leng-tech
        run: curl -s https://leng-tech.com || echo "Ping failed"
